Module5 task2
htmlacademy-react/597285-six-cities-10 pull request #12
Opened 2022-08-14 10:39 UTC by faderd

2022-08-14 17:03 UTC, bini1988 requested changes
Есть крит замечания, плюс нужно поправить предложения по близости согласно ТЗ (убрать логику выделения маркера при наведении на карточку):

> Под списком отзывов отображается карта с предложениями неподалёку. На карте отмечено 3 предложения неподалёку и маркер текущего предложения (итого 4 маркера). Маркеры предложений выделены синим. Маркер текущего предложения выделен оранжевым. Другая функциональность для карты с предложениями неподалёку не предусмотрена.

2022-08-14 17:03 UTC, bini1988 commented on project/src/components/property-location-list/property-location-list.tsx
> +    <OffersList offersListSetting={OffersListSetting} onActiveCardIdChange={onActiveCardIdChange} offers={offers} />
Кажется в компоненте `OffersList` нет большого смысла, проще от него везед избавиться и писать прямо:
```tsx
offers.map(offer => (
    <OfferCard 
      key={offer.id} 
      offer={offer}
      wrapperClassName="near-places__list places__list'"
      className="near-places__card"
      imgWrapperClassName="near-places__image-wrapper"
      imgWidth="260"
      imgHeight="200"
      infoClassName="place-card__info"
    />
))
```

2022-08-14 17:03 UTC, bini1988 commented on project/src/pages/main-screen/main-screen.tsx
> +              <OffersList onActiveCardIdChange={setActiveCardId} offersListSetting={OffersListSetting} offers={offers} />
И здесь тоже кажется лучше заинланить логику `OffersList`, тем более что это простой map по `offers`

2022-08-15 14:50 UTC, faderd commented on project/src/components/map/map.tsx
> +      style={mapSetting.Style}
На странице ProperyScreen карта выглядит не как в шаблоне - растягивается на всю ширину, поэтому такое решил добавить.

2022-08-15 19:22 UTC, bini1988 approved these changes

2022-08-15 19:22 UTC, bini1988 commented on project/src/components/user-menu/user-menu.tsx
> +  if (useAppSelector(isUserAuthorized)) {
Давай выносить в переменную `const isAuthorized = useAppSelector(isUserAuthorized)`, лучше не использвать вызов хуков в условных выражениях а поднимать их к началу функции компонента

2022-08-15 19:22 UTC, bini1988 commented on project/src/components/map/map.tsx
> +      }
В целом можно положить текущий объект предложения в массив `offers` вместе с предложения рядом внутри селектора `getNearbyOffers`, чтобы использовать только `selectedOfferId`

2022-08-15 19:22 UTC, bini1988 commented on project/src/components/map/map.tsx
> +      style={mapSetting.Style}
В шаблоне это просто картинка, реальная карта может растягиваться на всю ширину страницы

2022-08-15 19:22 UTC, merged