Module6 task2
htmlacademy-react/597285-six-cities-10 pull request #13
Opened 2022-08-16 14:46 UTC by faderd

Выдает ошибки на типы, что-то запутался с ними.

2022-08-16 20:33 UTC, bini1988 requested changes
Выглядит хорошо, предлагаю внести небольшие улучшения

2022-08-16 20:33 UTC, bini1988 commented on project/src/components/map/map.tsx
> +  mapClassName: string,
Можно просто `className`, обычно такой пропс подразумевает, что переданный css класс будет передан на контейнет компонента

2022-08-16 20:33 UTC, bini1988 commented on project/src/components/property-map/property-map.tsx
> +  const offers = [...useAppSelector(getNearbyOffers), currentOffer];
Я бы предложил всетаки спрятать эту логику внутрь селектора:
```ts
export const getNearbyOffers = (id: number) => (state: State) => {};
```
Тогда этот массив можно будет завернуть в createSelector и мемоизировать результат

2022-08-16 20:33 UTC, bini1988 commented on project/src/components/sorting-form/sorting-form.tsx
> +        tabIndex={sortingTypes.findIndex((type) => type === sortingType)}
А для чего здесь `tabIndex` задается таких хитрым способом?

2022-08-16 20:33 UTC, bini1988 commented on project/src/components/sorting-form/sorting-form.tsx
> +        dispatch(storeSortingType(sortingTypes[target.tabIndex]));
Давай не использовать DOM аттрибуты для передачи данных, тем более через tabIndex, который предназначени для других целей, а делать такие элементы через js замыкания

2022-08-16 20:33 UTC, bini1988 commented on project/src/components/sorting-form/sorting-form.tsx
> +      <ul className={`places__options places__options--custom ${isPlacesSortingOpened && 'places__options--opened'}`} onClick={({ target }: MouseEvent<HTMLUListElement>) => {
`isPlacesSortingOpened && 'places__options--opened'` может вернуть класс `false` в DOM элементы, в целом для таких целей удобно использовать пакет [classnames](https://www.npmjs.com/package/classnames).

2022-08-16 20:33 UTC, bini1988 commented on project/src/components/sorting-form/sorting-form.tsx
> +  const sortingTypes = Array.from(Object.values(SortingType));
А почему не хранить `SortingType` в виде массива? Плюс я бы разделил значения и лейблы для пунктов меню, на случай если появится русская версия сайта:

```ts
const SORTING_TYPES = [
  {value: SortingType.Popular, label: 'Popular'},
  {value: SortingType.PriceLowToHigh, label: 'Price: low to high'},
  {value: SortingType.PriceHighToLow, label: 'Price: high to low'},
  {value: SortingType.TopRatedFirst, label: 'Top rated first'},
];
```

Плюс `Object.values`  не всегда гарантирует порядок возвращаемых значений

2022-08-16 20:33 UTC, bini1988 commented on project/src/components/sorting-form/sorting-form.tsx
> +            <li key={`${index + 1}`} className={`places__option ${type === sortingType ? 'places__option--active' : ''}`} tabIndex={index}>{type}</li>
Можно использовать значени в качестве ключа

2022-08-16 20:33 UTC, bini1988 commented on project/src/pages/main-screen/main-screen.tsx
> +  console.log(sortingType);
Нужно удалять `console.log`

2022-08-16 20:33 UTC, bini1988 commented on project/src/store/app-data/app-data.ts
> +const DEFAULT_SORING_TYPE = SortingType.Popular;
В целом можно не выносить данное значение в константу если оно больше нигде не используется

2022-08-17 09:30 UTC, faderd commented on project/src/components/property-map/property-map.tsx
> +  const offers = [...useAppSelector(getNearbyOffers), currentOffer];
Что-то сделал, но, видимо, не совсем то..

2022-08-17 14:23 UTC, bini1988 approved these changes

2022-08-17 14:23 UTC, bini1988 commented on project/src/components/sorting-form/sorting-form.tsx
> +  const getSortingTypeLabel = () => SORTING_TYPES.find((type) => type.value === sortingType)?.label || null;
Чтобы не искать каждый раз выбранное значение в массиве, можно положить в стор весь объект выбранного элемента списка
```ts
{label: 'Popular', value: 'Popular'}
```
На практике это удобно, поскольку внутри такого объекта можно хранить связанные с элементом списка данные и удобно использовать их без необходимости поиска

2022-08-17 14:23 UTC, bini1988 commented on project/src/utils/common.ts
> +const filters: {[key: string]: (arg0: Offers) => Offers} = {
Давай давать аргументам функции осмысленные названия `{[key: string]: (offers: Offers) => Offers}`

2022-08-17 14:23 UTC, merged

2022-08-17 14:24 UTC, bini1988 commented on project/src/components/app/app.test.tsx
> +  DATA: { isDataLoaded: true, offers: offers, city: DEFAULT_CITY, reviews: [], nearbyOffers: offers, sortingType: DEFAULT_SORING_TYPE },
Я бы посоветовал не дубливать руками, а импортировать и вызывать функцию `getInitialStateAppData` чтобы создать копию исходного состояния