Module7 task3
htmlacademy-react/597285-six-cities-10 pull request #14
Opened 2022-08-20 16:54 UTC by faderd

2022-08-20 18:09 UTC, bini1988 requested changes
> Когда пользователь переходит на страницу с детальной информацией о предложении (/offer/:id), с сервера должна быть запрошена информация только по этому предложению

Сейчас на странице предложения запрашивается польный список, нужно это поправить

Давай также сделаем пукты из ТЗ
- https://up.htmlacademy.ru/react/10/project/six-cities#offerPageReviews
- https://up.htmlacademy.ru/react/10/project/six-cities#offerPageReviewForm

2022-08-20 18:09 UTC, bini1988 commented on project/src/store/api-actions.ts
> +export const pushActionFavoriteOffer = createAsyncThunk<Offer, {offerId: string, actionStatus: FavoriteActionStatus}, {
`push` несет доволно специфический смысл, тут по смыслу что-то вроде `toggleFavoriteOffer`

2022-08-20 18:09 UTC, bini1988 commented on project/src/store/api-actions.ts
> +export const pushReview = createAsyncThunk<Review, {offerId: string, review: {comment: string, rating: number}}, {
А тут `submitReview`

2022-08-21 18:19 UTC, faderd commented
> Сейчас на странице предложения запрашивается польный список, нужно это поправить

Получается, полный список запрашивается, потому-что в index.tsx в самом начале прописано store.dispatch(fetchOffers())
В задании module7-task1 в п. 4 было написано: "Список предложений должен загружаться при старте приложения."

Получается коллизия какая-то в требованиях. Но а в ТЗ прям про это не сказано, что в какой последовательности должно с сервера запрашиваться..

2022-08-21 18:24 UTC, bini1988 commented
> Получается коллизия какая-то в требованиях. Но а в ТЗ прям про это не сказано, что в какой последовательности должно с сервера запрашиваться.

В домашнем задании сказано что:

> Напишите всю необходимую логику для получения информации по одному предложению об аренде на странице «Room». Когда пользователь переходит на страницу с детальной информацией о предложении (/offer/:id), с сервера должна быть запрошена информация только по этому предложению.

То есть `Список предложений должен загружаться при старте приложения`  нужно уточнить до `Список предложений должен загружаться при старте приложения с главной страницы`

2022-08-21 18:53 UTC, bini1988 commented on project/src/store/app-data/app-data.ts
> +      const reviews = Array.from(action.payload)
Обычно логику преобразования данных выносят в селекторы, поскольку те же данные могут использоваться на странице для разных целей и не всегда текущая логика сортировки и обрезания массив будет актуально, например, как мы узнаем число оставленных отзывов если список всегда обрезается до 10?

2022-08-21 18:53 UTC, bini1988 commented on project/src/api.ts
> +  [StatusCodes.NOT_FOUND]: true
Тут больше подходит массив или `Set`

```ts
[StatusCodes.BAD_REQUEST, StatusCodes.UNAUTHORIZED, StatusCodes.NOT_FOUND].includes(response.status)
```

2022-08-21 18:53 UTC, bini1988 commented on project/src/components/bookmark-button/bookmark-button.tsx
> +  buttonClassName: string;
Можно просто `className`

2022-08-21 18:53 UTC, bini1988 commented on project/src/components/bookmark-button/bookmark-button.tsx
> +    ? buttonClassNameActive
Кажется `buttonClassNameActive` можно не передавать, а использовать `${buttonClassName}--active`

2022-08-21 18:53 UTC, bini1988 commented on project/src/components/form-submit-comment/form-submit-comment.tsx
> +            setSubmitting(false);
`setSubmitting(false);` встречается в обеих ветках if, можно упростить до

```ts
if (data.payload) {
     setComment('');
     setRating(0);
}
setSubmitting(false);
```

2022-08-21 18:53 UTC, bini1988 commented on project/src/components/form-submit-comment/form-submit-comment.tsx
> +        dispatch(submitReview({ offerId, review: { comment: comment, rating: rating } })).then((data) => {
Имхо но `{ comment, rating }` как-то проще читать, я бы предложил отдавать предпочтение такой записи

2022-08-21 18:53 UTC, bini1988 commented on project/src/store/api-actions.ts
> +export const submitReview = createAsyncThunk<Review, { offerId: string, review: { comment: string, rating: number } }, {
` { comment: string, rating: number }` кажется для удобства можно вынести в глобальный тип и использовать тут и в компоненте

2022-08-21 18:53 UTC, bini1988 commented on project/src/store/app-data/selectors.ts
> +    favoriteOffers.forEach((offer) => {
В целом решение рабочее, но не оптимальное, представь если у нас будет миллион предложений, каждое в уникальном городе, тогда твоя реализация соверши 1M + 1M * 1M итераций, хотя очевидно что сгруппировать список можно и за 1M + 1M итераций или даже за 1M если порядок отображения городов нам не важен.

Сейчас это не критично, но я бы посоветовал подумать как можно улучшить данный код.

2022-08-22 11:48 UTC, merged