Обратная сторона реальности
htmlacademy-react/597285-six-cities-10 pull request #5
Opened 2022-07-20 11:52 UTC by faderd

---
:mortar_board: [Обратная сторона реальности](https://up.htmlacademy.ru/react/10/user/597285/tasks/6)

2022-07-20 17:33 UTC, bini1988 requested changes
По ТЗ кажетс все ок, нужно пройтись по замечаниям, поправить нейминг,  удалить дублирующую верстку и поправить key пропс

2022-07-20 17:33 UTC, bini1988 commented on project/src/components/form-submit-comment/form-submit-comment.tsx
> +  const [commentFormState, setCommentFormState] = useState<string>('');
Здесь и ниже не обязательно указывать тип `string` или `number` если в `useState` передано значение по умолчанию

2022-07-20 17:33 UTC, bini1988 commented on project/src/components/form-submit-comment/form-submit-comment.tsx
> +  console.log(commentFormState, rateFormState);
В коде нельзя оставлять `console.log`

2022-07-20 17:33 UTC, bini1988 commented on project/src/components/form-submit-comment/form-submit-comment.tsx
> +      </div>
Давай отрендерим элементы рейтинга в цикле от 5 до 1 чтобы убрать дублирование верстки

2022-07-20 17:33 UTC, bini1988 commented on project/src/components/offer-card/offer-card.tsx
> +          <Link to={`${AppRoute.Room}/${offer.id}`}>{offer.title}</Link>
Здесь аналогично url лучше собрать через [generatePath](https://v5.reactrouter.com/web/api/generatePath)

2022-07-20 17:33 UTC, bini1988 commented on project/src/components/offer-card/offer-card.tsx
> +  const isItFavorite = (isFavorite: boolean): string => isFavorite ? 'place-card__bookmark-button--active ' : '';
В целом можно обойтись без функции 
```ts
const favoriteClassName = offer.isFavorite ? 'place-card__bookmark-button--active ' : '';
```
Плюс нейминг функции с `is`  намекает что она возвращает значение типа boolean, лучше не нарушать данное общепринятое соглашение

2022-07-20 17:33 UTC, bini1988 commented on project/src/components/offers-list/offers-list.tsx
> +  console.log(activeCardId);
После дебага все `console.log` нужно удалить

2022-07-20 17:33 UTC, bini1988 commented on project/src/components/offers-list/offers-list.tsx
> +        offersForRender.map((offer, id) => {
`index` вместо `id`, если код разрастется то сходу можно не понять что под `id` тут имеется ввиду индекс массива, поэтому лучше именовать такие вещи явно

2022-07-21 18:55 UTC, faderd commented on project/src/components/form-submit-comment/form-submit-comment.tsx
> +  console.log(commentFormState, rateFormState);
Тут вставил console.log чтобы eslint не ругался на неиспользуемые переменные commentFormState, rateFormState. Не знаю, как в таких случаях правильно поступать?

2022-07-21 18:56 UTC, faderd commented on project/src/components/offers-list/offers-list.tsx
> +            <OfferCard key={keyValue} offer={offer} onMouseOver={() => setActiveCardId(offer.id)} />
Не совсем понял, что имеется в виду?

2022-07-22 10:22 UTC, bini1988 approved these changes

2022-07-22 10:22 UTC, bini1988 commented on project/src/components/form-submit-comment/form-submit-comment.tsx
> +  const [ratingFormState, setRatingFormState] = useState(0);
Имхо но тут нет необходимости уточнять до `FormState` это и так понятно из контекста, поскольку мы уже находимся внутри комопнента `ReviewForm`, но не крит, можно оставить как есть

2022-07-22 10:22 UTC, bini1988 commented on project/src/components/form-submit-comment/form-submit-comment.tsx
> +  };
Можно сделать более компактную запись:

```tsx
{Array.from({length: 5}).map((_, index, arr) => {
   const value = arr.length - index;
   return <></>
})}
```

2022-07-22 10:22 UTC, bini1988 commented on project/src/components/offer-card/offer-card.tsx
> +    : 'place-card__info';
Как вариант можно просто вынести эти значения в пропсы и передавать значения снаружи:

```tsx
<OfferCard 
   className="favorites__card" 
   classNameWrapper="favorites__image-wrapper"
   imgWidth="150"
   imageHeight="110"
/>
```

2022-07-22 10:22 UTC, merged